# Generated by Django 4.1.13 on 2024-08-18 06:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogger', '0003_comment_comment_blogger_com_created_b20b17_idx'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='body',
            field=models.TextField(default='This is the body of the comment'),
            preserve_default=False,
        ),
    ]
